language: php
php:
  - 7.2
  - 7.3
  
services:
  - mysql
  
before_script:
    - cp config/.env.example config/.env
    - cp config/app_local.example.php config/app_local.php
    - sh -c mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    
script:
  - bash vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
    
notifications:
  email: false  