name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '*'
env:
      DB_DATABASE: cakephp
      DB_USER: root
      DB_PASSWORD: root
jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.4']
        db-type: [mysql]
        include:
          - php-version: '7.2'
            db-type: 'mysql'
        
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up MySQL
      run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    
    - name: Composer install
      run: | 
          composer update 
          composer install
    
    - name: arquivos
      run: |
         cp config/.env.example config/.env
         cp config/app_local.example.php config/app_local.php
       
    - name: Run PHPUnit
      run: |       
       if [[ ${{ matrix.php-version }} == '7.4' ]]; then
          vendor/bin/phpunit --verbose --coverage-clover=coverage.xml
        else
          vendor/bin/phpunit
        fi
   
    - name: Code Coverage Report
      if: matrix.php-version == '7.4' 
      uses: codecov/codecov-action@v1
     
